[project]
name = "mloca"
version = "0.1.5"
description = ""
authors = [
    {name = "MMiirrkk",email = "cot@wp.pl"}
]
license = {text = "Apache 2.0"}
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
numpy = [
  { version = "^2.4.4", python = ">=3.11" },
  { version = "^1.26", python = ">=3.10,<3.11" }
]
scikit-learn = ">=1.8.0,<2.0.0"


[tool.poetry]
packages = [
    {include = "mloca"}
]
include = [
    {path = "mloca/focus_model/models/*.pkl", format = ["sdist", "wheel"]}
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
